#pragma once

//#define TEST_RING_BUFFER
//#define TEST_VARIABLE_STRING
//#define TEST_LOGGER
//#define TEST_STRING_STREAM
//#define TEST_FT
//#define TEST_SORT
//#define TEST_NETWORK
//#define TEST_FILE_STREAM
//#define TEST_NETWORK_STREAM
//#define TEST_INI
//#define TEST_FTP
//#define TEST_MODBUS_UDP
//#define TEST_THREAD
//#define TEST_FILE
//#define TEST_UART
//#define TEST_LOCK
//#define TEST_VIRTUAL_ALLOCATOR
//#define TEST_FILE_ALLOCATOR
//#define TEST_MEM_INFO
//#define TEST_DISK
//#define TEST_ARRAY
//#define TEST_NETWORK_INTERFACE
#define TEST_ARG_PARSER